# Generated by Django 3.0.8 on 2020-10-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subreddits',
            name='description',
            field=models.CharField(max_length=5000),
        ),
    ]
