# Generated by Django 3.0.8 on 2020-10-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0002_auto_20201009_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subreddits',
            name='description',
            field=models.CharField(max_length=1100),
        ),
    ]
