# Generated by Django 3.0.8 on 2020-10-09 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0003_auto_20201009_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subreddits',
            name='description',
        ),
    ]
